import test from 'node:test';
import assert from 'node:assert/strict';
import {makeProof,parseProof,hashFile,receiptFromParsed,MEMO_PROGRAM,MAX_FILE_BYTES} from '../src/proof.mjs';
const hash='ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad';
const proof=makeProof('Website handover',hash);
test('hashes local bytes using the standard SHA-256 known answer',async()=>assert.equal(await hashFile(new File(['abc'],'private-name.txt')),hash));
test('does not read oversized files',async()=>{let read=false;await assert.rejects(hashFile({size:MAX_FILE_BYTES+1,arrayBuffer(){read=true;}}),/50 MB/);assert.equal(read,false);});
test('accepts the empty-file SHA-256',async()=>assert.equal(await hashFile(new File([],'empty')), 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'));
test('receipt payload includes no filename or bytes',()=>assert.deepEqual(Object.keys(proof).sort(),['app','label','sha256','v']));
test('valid proof round trip',()=>assert.deepEqual(parseProof(JSON.stringify(proof)),proof));
for(const label of ['', '  ', 'x'.repeat(121),'🍪'.repeat(31),'label\u202etxt','label\nsecret'])test('rejects unsafe label '+JSON.stringify(label).slice(0,30),()=>assert.throws(()=>makeProof(label,hash)));
test('counts labels in UTF-8 bytes',()=>assert.equal(makeProof('🍪'.repeat(30),hash).label.length,60));
for(const sha of [hash.toUpperCase(),'a'.repeat(63),null,123])test('rejects invalid fingerprint '+String(sha).slice(0,10),()=>assert.throws(()=>makeProof('test',sha)));
for(const p of [{...proof,v:2},{...proof,app:'other'},{...proof,secret:'unexpected'},null,[],{}])test('rejects incompatible payload '+JSON.stringify(p).slice(0,32),()=>assert.equal(parseProof(JSON.stringify(p)),null));
const tx=()=>({meta:{err:null,fee:5000},slot:12,blockTime:123,transaction:{message:{accountKeys:[{pubkey:'signer-address',signer:true}],instructions:[{programId:MEMO_PROGRAM,parsed:JSON.stringify(proof)}]}}});
test('reads a successful Memo receipt and its actual signer',()=>{const r=receiptFromParsed(tx(),'sig');assert.equal(r.signer,'signer-address');assert.equal(r.sha256,hash);assert.equal(r.blockTime,123);});
test('failed chain transaction cannot be a receipt',()=>{const t=tx();t.meta.err={InstructionError:[0,'error']};assert.equal(receiptFromParsed(t,'sig'),null);});
test('a transfer plus a Memo is not accepted as this app receipt',()=>{const t=tx();t.transaction.message.instructions.push({programId:'transfer'});assert.equal(receiptFromParsed(t,'sig'),null);});
test('another program cannot masquerade as a Memo',()=>{const t=tx();t.transaction.message.instructions[0].programId='other';assert.equal(receiptFromParsed(t,'sig'),null);});
test('missing signer rejects receipt',()=>{const t=tx();t.transaction.message.accountKeys[0].signer=false;assert.equal(receiptFromParsed(t,'sig'),null);});
test('unavailable transaction rejects receipt',()=>assert.equal(receiptFromParsed(null,'sig'),null));
