import React,{useEffect,useRef,useState} from 'react';
import {ExternalLink,RefreshCw} from 'lucide-react';
import {makeProof,hashFile,shorten} from './proof.mjs';
import {connectNightly,disconnectNightly,prepareProof,signAndPublish,checkStatus,getReceipt,recentReceipts,readPending,clearPending,connection,standardOf} from './chain.mjs';
import {Mark,Notice,FilePicker,Explanation,ReviewDialog,Receipt,Help} from './components.jsx';
import {PublicKey} from '@solana/web3.js';

function useLocalFile(){
 const [file,setFile]=useState(null),[hash,setHash]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),generation=useRef(0);
 const choose=async(next,problem)=>{const id=++generation.current;setFile(null);setHash('');setError(problem||'');if(!next){setBusy(false);return;}setBusy(true);try{const value=await hashFile(next);if(generation.current!==id)return;setHash(value);setFile(next);}catch(e){if(generation.current===id)setError(e.message);}finally{if(generation.current===id)setBusy(false);}};
 return {file,hash,busy,error,choose};
}
export default function App(){
 const initialTx=new URLSearchParams(location.search).get('tx')||'';
 const [tab,setTab]=useState(initialTx?'verify':'create'),[session,setSession]=useState(null),[walletBusy,setWalletBusy]=useState(false),[balance,setBalance]=useState(null),[notice,setNotice]=useState(''),[review,setReview]=useState(null),[busy,setBusy]=useState(false),[label,setLabel]=useState(''),[receipt,setReceipt]=useState(null),[pending,setPending]=useState(readPending),[status,setStatus]=useState(''),[signature,setSignature]=useState(initialTx),[verification,setVerification]=useState(null),[history,setHistory]=useState(null);
 const file=useLocalFile(),verifyFile=useLocalFile();
 const sessionRef=useRef(session);sessionRef.current=session;
 async function connect(){setWalletBusy(true);setNotice('');try{const s=await connectNightly();setSession(s);setReview(null);connection.getBalance(new PublicKey(s.account.address)).then(setBalance).catch(()=>setBalance(null));return s;}catch(e){setNotice(e.message);return null;}finally{setWalletBusy(false);}}
 async function disconnect(){try{await disconnectNightly(session);}catch{}setSession(null);setBalance(null);setReview(null);}
 useEffect(()=>{const events=session?.wallet.features['standard:events'];if(!events)return;return events.on('change',change=>{if(change.accounts){const next=change.accounts[0];setReview(null);if(!next){setSession(null);setBalance(null);}else{setSession(s=>s?{...s,account:next}:null);setBalance(null);}}});},[session?.wallet]);
 const selectTab=next=>{setTab(next);setNotice('');setReview(null);};
 async function startReview(){
  setNotice('');setReceipt(null);try{const proof=makeProof(label,file.hash);if(file.busy)throw new Error('Wait for the file fingerprint to finish.');if(pending)throw new Error('Check the saved pending transaction before publishing another proof.');setBusy(true);const s=session||await connect();if(!s)return;const value=await prepareProof(s,proof);setReview(value);}catch(e){setNotice(e.message);}finally{setBusy(false);}
 }
 async function reconcile(sig=pending?.signature){
  if(!sig)return;setBusy(true);setNotice('');try{const saved=readPending();const state=await checkStatus(sig,saved?.signature===sig?saved.lastValidBlockHeight:undefined);setStatus(state);if(state==='confirmed'){const found=await getReceipt(sig);setReceipt(found);clearPending();setPending(null);setReview(null);}else if(state==='failed'){setNotice('This transaction failed on-chain. It did not create a valid receipt. You can review a new proof.');clearPending();setPending(null);}else if(state==='expired'){setNotice('The signing window expired and this RPC returned no transaction record. Check the explorer before deciding to create another proof.');}else{setNotice('Confirmation is still unresolved. Keep the signature and check again before creating a duplicate.');}}catch(e){setNotice(e.message);}finally{setBusy(false);}
 }
 async function publish(){
  setBusy(true);setNotice('');try{const sig=await signAndPublish(sessionRef.current,review);setPending({signature:sig,...review.proof});setReview(null);setStatus('pending');await reconcile(sig);}catch(e){if(e.signature){setPending({signature:e.signature,...review.proof});setReview(null);setStatus('unresolved');}setNotice(e.message);}finally{setBusy(false);}
 }
 async function verify(sig=signature){setBusy(true);setNotice('');setVerification(null);try{setVerification(await getReceipt(sig.trim()));}catch(e){setNotice(e.message);}finally{setBusy(false);}}
 useEffect(()=>{if(initialTx)verify(initialTx);},[]);
 async function loadHistory(){setBusy(true);setNotice('');try{const s=session||await connect();if(!s)return;setHistory(await recentReceipts(s.account.address));}catch(e){setNotice(e.message);}finally{setBusy(false);}}
 return <div className="shell"><header><button className="brand" onClick={()=>selectTab('create')} aria-label="Crumbproof home"><Mark/><span>crumbproof</span></button><nav aria-label="Main navigation">{[['create','Create proof'],['verify','Verify proof'],['history','My receipts']].map(([key,text])=><button key={key} className={tab===key?'active':''} aria-current={tab===key?'page':undefined} onClick={()=>selectTab(key)}>{text}</button>)}</nav><button className="wallet" onClick={session?disconnect:connect} disabled={walletBusy} title={session?'Disconnect '+session.account.address:undefined}>{walletBusy?'Connecting…':session?shorten(session.account.address):'Connect Nightly'}</button></header>
 <main><div className="intro"><h1>{tab==='create'?'Give your work a timestamp.':tab==='verify'?'Check the work. Verify the proof.':tab==='history'?'Your work, on record.':'A little proof goes a long way.'}</h1><p>{tab==='create'?'Create a public receipt on Cookie Chain. Your file stays on your device.':tab==='verify'?'Look up a confirmed receipt, then compare it with the file on your device.':tab==='history'?'Find Crumbproof receipts among your wallet’s 20 most recent transactions.':'Understand what your receipt records, and what remains on your device.'}</p></div>
 <Notice message={notice}/>
 {tab==='create'&&<><div className="workspace"><section className="panel"><h2>Create a proof</h2><label htmlFor="label">Public label</label><input id="label" value={label} onChange={e=>{setLabel(e.target.value);setReview(null);setReceipt(null);}} maxLength={120} placeholder="e.g. Website handover · v1"/>
 <FilePicker onChange={(f,p)=>{setReview(null);setReceipt(null);file.choose(f,p);}} selected={file.file} hashing={file.busy} error={file.error}/>
 <div className="fingerprint"><label>SHA-256 fingerprint</label><code>{file.hash||'Choose a file to calculate its fingerprint.'}</code></div>
 <button className="primary review-button" onClick={startReview} disabled={busy||file.busy}>{busy?'Preparing review…':'Review proof'}</button><p className="muted small">You will review the public details and network fee before signing.</p></section><Explanation/></div>
 <div className="public-strip"><strong>What becomes public?</strong><span>Your wallet address, public label and file fingerprint. Keep confidential details out of the label.</span></div>
 {pending&&<section className="panel pending"><h2>{status==='unresolved'?'Broadcast outcome unresolved':'Proof awaiting confirmation'}</h2><p>Keep this signature. Check its status before publishing again.</p><code className="break">{pending.signature}</code><div className="actions"><button className="primary" disabled={busy} onClick={()=>reconcile()}><RefreshCw size={16}/> Check status</button><a href={'https://cookiescan.io/tx/'+pending.signature} target="_blank" rel="noreferrer">Open explorer</a>{status==='expired'&&<button onClick={()=>{clearPending();setPending(null);setStatus('');setNotice('Local pending marker cleared. Keep your old signature and verify its history before making another receipt.');}}>Clear expired local marker</button>}</div></section>}
 {receipt&&<Receipt receipt={receipt}/>}</>}
 {tab==='verify'&&<section className="panel verify-panel"><h2>Verify a receipt</h2><form onSubmit={e=>{e.preventDefault();verify();}}><label htmlFor="signature">Transaction signature</label><div className="input-row"><input id="signature" value={signature} onChange={e=>{setSignature(e.target.value);setVerification(null);}} placeholder="Paste a Cookie Chain transaction signature"/><button className="primary" disabled={busy}>{busy?'Checking…':'Look up proof'}</button></div></form>
 {verification&&<><Receipt receipt={verification}/><h3>Compare a local file</h3><FilePicker onChange={verifyFile.choose} selected={verifyFile.file} hashing={verifyFile.busy} error={verifyFile.error}/>{verifyFile.hash&&<div role="status" className={'match '+(verifyFile.hash===verification.sha256?'yes':'no')}>{verifyFile.hash===verification.sha256?'Exact match. This file has the fingerprint recorded in the receipt.':'No match. This file differs from the fingerprint in this receipt.'}</div>}</>}</section>}
 {tab==='history'&&<section className="panel"><div className="section-top"><h2>My receipts</h2><button className="primary" disabled={busy} onClick={loadHistory}>{busy?'Reading chain…':'Refresh receipts'}</button></div>{session&&<p className="muted">Wallet <code>{session.account.address}</code>{balance!==null?' · '+(balance/1e9).toLocaleString(undefined,{maximumFractionDigits:6})+' COOK':''}</p>}
 {!history?<p>Connect Nightly and refresh to read your recent receipts.</p>:<><p className="muted">Checked {history.checked} recent transactions. Older receipts can be looked up by signature.</p>{history.unavailable>0&&<Notice message={history.unavailable+' transactions could not be read. These results are incomplete; refresh to try again.'}/>}{history.receipts.length?<div className="history">{history.receipts.map(r=><button key={r.signature} onClick={()=>{setSignature(r.signature);setVerification(r);selectTab('verify');}}><span><strong>{r.label}</strong><code>{shorten(r.sha256,12)}</code></span><span>{r.blockTime?new Date(r.blockTime*1000).toLocaleDateString():'Block time unavailable'} <ExternalLink size={16}/></span></button>)}</div>:<p>No supported receipts were found among the transactions that could be read.</p>}</>}</section>}
 {tab==='help'&&<Help/>}
 </main><footer><button onClick={()=>selectTab('help')}>How it works</button><a href="https://cookiescan.io" target="_blank" rel="noreferrer">Cookie Chain explorer</a><a href="https://github.com/Zyphrae/crumbproof-cookie-chain" target="_blank" rel="noreferrer">Source code</a>{session&&<span className="connected-note">Nightly connected · {shorten(session.account.address)}</span>}</footer>
 {review&&<ReviewDialog review={review} busy={busy} onClose={()=>setReview(null)} onPublish={publish}/>}</div>;
}
